# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080


RUN   sed -i "/s/LISTEN 80/LISTEN 8080/g" /etc/httpd/cong/httpd.conf \
RUN   sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" \
      /etc/httpd/conf/httpd.conf

RUN   chgrp -R 0 /var/log/httpd /var/run/httpd && \
      chmod -R g=u /var/log/httpd /var/run/httpd
USER  1001
